apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: demo-dev
  namespace: demo-dev
spec:
  # Default values
  # https://github.com/tongueroo/helm-app/blob/main/values.yaml
  values:
    image:
      pullPolicy: Always
      repository: tongueroo/demo-nginx
      tag: kubes-2023-03-13T19-22-06
