apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: app1-dev
  namespace: app1-dev
spec:
  # releaseName: demo-dev
  chart:
    spec:
      chart: app
      sourceRef:
        kind: HelmRepository
        name: helm-repo
  interval: 10s
  install:
    remediation:
      retries: 3
  values:
    image:
      pullPolicy: Always
      repository: tongueroo/demo-nginx
      tag: kubes-2023-03-13T19-22-06
